# Generated by Django 4.0.6 on 2023-04-09 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_item_image2_item_image3_item_status_item_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='price2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.IntegerField(choices=[(0, 'Brand new item'), (1, 'Used item'), (0, 'Other')], default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='stock',
            field=models.IntegerField(choices=[(0, 'Single (1 item)'), (1, 'Medium (2-10 items)'), (2, 'Large (11-100 items)'), (3, 'Extra-large (101-1000 items)'), (4, 'Unlimited (>1000 items)')], default=0),
        ),
    ]
