# Generated by Django 4.0.6 on 2023-04-10 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_item_price2_alter_item_status_alter_item_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.IntegerField(choices=[(0, 'Brand new item'), (1, 'Used item'), (2, 'Other')], default=0),
        ),
    ]
