# Generated by Django 4.0.6 on 2023-04-11 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_alter_item_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, default='default_images/default_image_item.jpg', null='True', upload_to='item_image'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image2',
            field=models.ImageField(blank=True, default='default_images/default_image2_item.jpg', null='True', upload_to='item_image2'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image3',
            field=models.ImageField(blank=True, default='default_images/default_image3_item.jpg', null='True', upload_to='item_image3'),
        ),
    ]
