# Generated by Django 4.0.6 on 2023-04-16 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversationmessage',
            name='is_read',
        ),
    ]
